name:                aws-empty-content-encoding-issue
version:             0.1.0.0
github:              "mgajda/aws-empty-content-encoding-issue"
license:             BSD3
author:              "Michał J. Gajda"
maintainer:          "mjgajda@gmail.com"
copyright:           "Copyright &#39;2018 by Migamake Pte Ltd"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mgajda/aws-empty-content-encoding-issue#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- lens
- amazonka
- amazonka-s3

executables:
  aws-empty-content-encoding-issue-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

